In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print('Setup done')

Setup done


In [4]:
eeg_signal_database =  pd.read_csv('d:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/train/train/subj10_series1_data.csv')

In [5]:
eeg_signal_database.head()

id  Fp1  Fp2   F7   F3   Fz   F4   F8  FC5  FC1  ...   P7  \
0  subj10_series1_0 -304 -156 -411 -640 -505 -603 -451  104 -344  ... -197   
1  subj10_series1_1 -300 -151 -376 -670 -509 -622 -422   60 -374  ... -203   
2  subj10_series1_2 -286 -227 -400 -724 -525 -631 -469   70 -378  ... -176   
3  subj10_series1_3 -281 -272 -447 -702 -540 -640 -492   71 -386  ... -154   
4  subj10_series1_4 -294 -194 -432 -693 -503 -609 -500  109 -385  ... -146   

    P3   Pz   P4  P8  PO9   O1   Oz   O2  PO10  
0 -597 -242 -472 -56 -338 -335 -518 -371  -177  
1 -611 -224 -471 -53 -310 -326 -511 -396  -189  
2 -608 -234 -475 -78 -282 -289 -505 -424  -193  
3 -605 -246 -488 -73 -304 -337 -539 -412  -192  
4 -602 -226 -448 -25 -342 -333 -549 -400  -157  

[5 rows x 33 columns]

In [8]:
first_data = eeg_signal_database.iloc[1:3]
print(first_data)

                 id  Fp1  Fp2   F7   F3   Fz   F4   F8  FC5  FC1  ...   P7  \
1  subj10_series1_1 -300 -151 -376 -670 -509 -622 -422   60 -374  ... -203   
2  subj10_series1_2 -286 -227 -400 -724 -525 -631 -469   70 -378  ... -176   

    P3   Pz   P4  P8  PO9   O1   Oz   O2  PO10  
1 -611 -224 -471 -53 -310 -326 -511 -396  -189  
2 -608 -234 -475 -78 -282 -289 -505 -424  -193  

[2 rows x 33 columns]


In [2]:
events_database = pd.read_csv('d:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/train/train/subj10_series1_events.csv')

In [6]:
events_database.tail()

id  HandStart  FirstDigitTouch  BothStartLoadPhase  \
262382  subj10_series1_262382          0                0                   0   
262383  subj10_series1_262383          0                0                   0   
262384  subj10_series1_262384          0                0                   0   
262385  subj10_series1_262385          0                0                   0   
262386  subj10_series1_262386          0                0                   0   

        LiftOff  Replace  BothReleased  
262382        0        0             0  
262383        0        0             0  
262384        0        0             0  
262385        0        0             0  
262386        0        0             0

In [4]:
events_database.isna().sum()


id                    0
HandStart             0
FirstDigitTouch       0
BothStartLoadPhase    0
LiftOff               0
Replace               0
BothReleased          0
dtype: int64

In [13]:
events_database.loc[events_database.HandStart ==1]

id  HandStart  FirstDigitTouch  BothStartLoadPhase  \
2530      subj10_series1_2530          1                0                   0   
2531      subj10_series1_2531          1                0                   0   
2532      subj10_series1_2532          1                0                   0   
2533      subj10_series1_2533          1                0                   0   
2534      subj10_series1_2534          1                0                   0   
...                       ...        ...              ...                 ...   
258287  subj10_series1_258287          1                0                   0   
258288  subj10_series1_258288          1                0                   0   
258289  subj10_series1_258289          1                0                   0   
258290  subj10_series1_258290          1                0                   0   
258291  subj10_series1_258291          1                0                   0   

        LiftOff  Replace  BothReleased  
2530          0        0             0  
2531          0        0             0  
2532          0        0             0  
2533          0        0             0  
2534          0        0             0  
...         ...      ...           ...  
258287        0        0             0  
258288        0        0             0  
258289        0        0             0  
258290        0        0             0  
258291        0        0             0  

[5100 rows x 7 columns]

In [1]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from glob import glob
import os 

from sklearn.preprocessing import StandardScaler

In [2]:
def prepare_data_train(fname):
    #read the data from the path given 
    data = pd.read_csv(fname)
    #read the events
    #reapcing the events from data to events 
    events_fname = fname.replace('_data', '_events')
    labels= pd.read_csv(events_fname)
    clean = data.drop(['id'], axis=1)
    labels= labels.drop(['id'], axis = 1)
    return clean, labels


In [3]:

subjects = range(1,13)
#ids_tot = []
#pred_tot = []

for subject in subjects:
    y_raw = []
    raw = []
    ############################# Read Data #####################
    fnames = glob('D:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/train/train/subj%d_series*_data.csv' %(subject))
    for fname in fnames:
        data,labels = prepare_data_train(fname)
        raw.append(data)
        y_raw.append(labels)
        
    X = pd.concat(raw)
    y = pd.concat(y_raw)
    
    X_train = np.asarray(X.astype(float))
    y = np.asarray(y.astype(float))
        

In [4]:
def prepare_data_test(fname):
    data = pd.read_csv(fname)
    return data


In [7]:
subjects = range(1,13)
ids_tot = []
for subject in subjects:
    fnames = glob('D:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/test/test/subj%d_series*_data.csv' %(subject))
    test = []
    idx = []
    for fname in fnames:
        data = prepare_data_test(fname)
        test.append(data)
        idx.append(np.array(data['id']))
    X_test = pd.concat(test)
    ids= np.concatenate(idx)
    ids_tot.append(ids)
    X_test= X_test.drop(['id'],axis=1)
    X_test = np.asarray(X_test.astype(float))

In [12]:
print(X_test)

[[-309.  495.  -54. ...   12.  -46.   11.]
 [-376.  431.  -85. ...    0.  -95. -133.]
 [-545.  413. -185. ...   22.  -67. -123.]
 ...
 [ -32.  234.  474. ...   17.   -7.   18.]
 [ -60.  195.  449. ...  -70. -140.   95.]
 [ -41.  186.  411. ...  -69.  -58.  194.]]


In [15]:
scaler= StandardScaler()
def data_preprocess_train(X):
    X_prep= scaler.fit_transform(X)
    return X_prep

def data_preprocess_test(X):
    X_prep=scaler.transform(X)
    return X_prep

subsample = 100

cols = ['HandStart','FirstDigitTouch','BothStartLoadPhase','LiftOff','Replace','BothReleased']

In [28]:
subjects = range(1,13)
pred_tot = []
for subject in subjects:
    lr = LogisticRegression()
    pred = np.empty((X_test.shape[0],6))
    X_train=data_preprocess_train(X_train)
    X_test=data_preprocess_test(X_test)
    for i in range(6):
        y_train= y[:,i]
        print('Train subject %d, class %s' % (subject, cols[i]))
        lr.fit(X_train[::subsample,:],y_train[::subsample])
        pred[:,i] = lr.predict_proba(X_test)[:,1]

    pred_tot.append(pred)

# submission file
submission_file = 'D:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/grasp-lift.csv'
# create pandas object for sbmission
submission = pd.DataFrame(index=np.concatenate(ids_tot),
                          columns=cols,
                          data=np.concatenate(pred_tot))

# write file
submission.to_csv(submission_file,index_label='id',float_format='%.3f')

Train subject 1, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 1, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 1, class BothStartLoadPhase
Train subject 1, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 1, class Replace
Train subject 1, class BothReleased

C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



Train subject 2, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 2, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 2, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 2, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 2, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 2, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 3, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 4, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 5, class HandStart
Train subject 5, class FirstDigitTouch

C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)



Train subject 5, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 5, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 5, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 5, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 6, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 7, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 8, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 9, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 10, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 11, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class HandStart


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class FirstDigitTouch


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class BothStartLoadPhase


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class LiftOff


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class Replace


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


Train subject 12, class BothReleased


C:\Users\prabh\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
subjects = range(1,13)
pred_tot = []
for subject in subjects:
    knn = KNeighborsClassifier(n_neighbors = 5, metric= 'minkowski', p=2)
    pred = np.empty((X_test.shape[0],6))
    X_train=data_preprocess_train(X_train)
    X_test=data_preprocess_test(X_test)
    for i in range(6):
        y_train= y[:,i]
        print('Train subject %d, class %s' % (subject, cols[i]))
        knn.fit(X_train[::subsample,:],y_train[::subsample])
        pred[:,i] = knn.predict_proba(X_test)[:,1]

    pred_tot.append(pred)

# submission file
submission_file = 'D:/Mtech-SemII/Major Project/grasp-and-lift-eeg-detection/grasp-lift.csv'
# create pandas object for sbmission
submission = pd.DataFrame(index=np.concatenate(ids_tot),
                          columns=cols,
                          data=np.concatenate(pred_tot))

# write file
submission.to_csv(submission_file,index_label='id',float_format='%.3f')

Train subject 1, class HandStart
